# Generated by Django 4.2.14 on 2024-08-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_order_deal"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="bank",
            field=models.CharField(default="Unknown Bank", max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="geo",
            field=models.CharField(default="Unknown Geo", max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="goal",
            field=models.CharField(default="Unknown Goal", max_length=100),
        ),
        migrations.AlterField(
            model_name="product", name="name", field=models.CharField(max_length=100),
        ),
    ]
