# Generated by Django 4.2.14 on 2024-08-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_bank_product_geo_product_goal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="liquidity",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product", name="bank", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="product", name="geo", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="product", name="goal", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="product", name="name", field=models.CharField(max_length=255),
        ),
    ]
