# Generated by Django 4.2.14 on 2024-08-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_product_liquidity_alter_product_bank_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="currency",
            field=models.CharField(default="USD", max_length=10),
        ),
    ]
